CREATE TABLE IF NOT EXISTS genres (
	genre_id BIGINT NOT NULL AUTO_INCREMENT,
	genre_name VARCHAR(14) NOT NULL,
	CONSTRAINT genres_pk PRIMARY KEY (genre_id)
);

CREATE TABLE IF NOT EXISTS mpa (
	mpa_id BIGINT NOT NULL AUTO_INCREMENT,
	mpa_name VARCHAR(5) NOT NULL,
	CONSTRAINT mpa_pk PRIMARY KEY (mpa_id)
);

CREATE TABLE IF NOT EXISTS users (
	user_id BIGINT NOT NULL AUTO_INCREMENT,
	email VARCHAR NOT NULL,
	login VARCHAR(255) NOT NULL,
	user_name VARCHAR(255),
	birthday DATE,
	CONSTRAINT users_pk PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS user_friends (
	user_id BIGINT NOT NULL,
	friend_id BIGINT NOT NULL,
	UNIQUE (user_id, frined_id),
	CONSTRAINT user_friends_pk PRIMARY KEY (user_id, friend_id),
	CONSTRAINT user_friends_fk FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS films (
	film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	film_name VARCHAR(255) NOT NULL,
	description VARCHAR(200),
	release_date DATE,
	duration INTEGER,
	mpa_id BIGINT NOT NULL,
	CONSTRAINT films_pk PRIMARY KEY (film_id),
	CONSTRAINT films_fk FOREIGN KEY (mpa_id) REFERENCES mpa(mpa_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS film_genre (
	film_id BIGINT REFERENCES films(film_id) ON DELETE CASCADE,
	genre_id BIGINT REFERENCES genre(genre_id) ON DELETE CASCADE,
	UNIQUE (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
	user_id BIGINT REFERENCES films(film_id) ON DELETE CASCADE,
	film_id BIGINT REFERENCES users(film_id) ON DELETE CASCADE,
	UNIQUE (user_id, film_id)
);